# Generated by Django 5.0.1 on 2024-01-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_to_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
