# Generated by Django 5.0.1 on 2024-01-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_article_title_alter_article_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='News',
        ),
    ]
