# Generated by Django 5.0.1 on 2024-01-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_rename_article_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='all_content',
            field=models.TextField(blank=True),
        ),
    ]
