# Generated by Django 5.0.1 on 2024-01-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_news_all_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='all_content',
        ),
    ]
